apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - verbs/deployment.yaml
  - verbs/service.yaml
  - nouns/deployment.yaml
  - nouns/service.yaml
  - aggregator/deployment.yaml
  - aggregator/service.yaml