apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - istio/peer-authentication.yaml
  - istio/authorization-policy.yaml
  - istio/gateway.yaml
  - istio/http-route.yaml
  - kyverno/admission/disallow-default-namespace.yaml
  - kyverno/admission/verify-image-registry.yaml
  - kyverno/admission/verify-liveness-probe.yaml
  - kyverno/mutate/add-default-ressource-limits.yaml
  - kyverno/mutate/add-default-security-context.yaml
  - verbs/deployment.yaml
  - verbs/service.yaml
  - nouns/deployment.yaml
  - nouns/service.yaml
  - aggregator/deployment.yaml
  - aggregator/service.yaml
  - aggregator/ingress.yaml