apiVersion: v1
kind: Service
metadata:
  name: agg
  namespace: ssi
spec:
  selector:
    name: agg
  ports:
    - name: aggs-port
      port: 8080
      protocol: TCP
      targetPort: 3000
  type: LoadBalancer