apiVersion: apps/v1
kind: Deployment
metadata:
  name: nouns
  namespace: ssi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nouns
      app: nouns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nouns
        app: nouns
        version: v1
    spec:
      containers:
        - name: nouns
          image: ghcr.io/murielparaire/ssi/nouns:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 15
            timeoutSeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10