apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-securitycontext
  annotations:
    policies.kyverno.io/title: Add Default Security Context
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: Set security context for each pod   
spec:
  rules:
  - name: add-default-securitycontext
    match:
      any:
      - resources:
          kinds:
            - Pod
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            +(runAsNonRoot): true
            +(runAsUser): 1000
            +(runAsGroup): 3000
            +(fsGroup): 2000