apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-resource-requests
  annotations:
    policies.kyverno.io/title: Add Default Resource Requests
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: Add default resource requests to any pods that don't have them      
spec:
  background: false
  rules:
  - name: add-resource-requests
    match:
      any:
      - resources:
          kinds:
            - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
            - (name): "*"
              resources:
                requests:
                  +(memory): "64Mi"
                  +(cpu): "250m"